### ISSUE TITLE
🔷 [Epic] People Recommendations

### ISSUE THREAD

**Issue by pkudinov** [near/data-platform#11]
```[tasklist]
### Tasks
- [x] onFollow: removal of profile card in LatestPeople component
- [x] All lists: loadMore: fix bug viewport scroll-y behavior, jumping to top of screen
- [x] Analytics: Investigate, why tracker sends events 200 OK to test source, but gets 400 sending to prod source
- [x] Add handling for 404, no source available
- [ ] https://github.com/near/near-discovery-components/pull/441
- [ ] https://github.com/near/near-databricks-lakehouse/pull/17
```
