### ISSUE TITLE
🔷 [Epic] New Ver. of Component Details Page with Preview + Metrics + Parent Components + Dev Info

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/data-platform#2]
### Description
This init
This is targeted to release by NEARCon

### Success Criteria
The details page include following information about the component

**NEARCon**
- Description, tags, last updated(commit) and other metadata of the component
- Impression: Number of times it was loaded through RPC (daily stats for past 30 days)
- Information about the creator of this component (number of days they are active, reputation score calculated from data such as num of components published/forked/used, lines of code, number of likes/save received etc.)
- Number of Interactions on this Component
- <Stretch> Total Parent Num + A list of parent component(with links to open these components) where this component is used in

**Post NEARCon when available**
- Number of times this component is forked 
- Number of likes and bookmark this component has received 
- Number of Times Rendering Errors

### Resources
(Relevant documentation, Figma links, and other reference material)

- [WIP redesigned component detail page ](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=902%3A5087&type=design&node-id=912-922&viewport=523%2C440%2C0.13&t=mZ1mzxnvfGvThrCg-1&scaling=min-zoom&mode=design)under review.

- [NEARCon Design](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=975%3A2&type=design&node-id=975-5073&viewport=511%2C1088%2C1&t=SM79BySZGdDUYW4R-1&scaling=min-zoom&starting-point-node-id=975%3A5290&show-proto-sidebar=1)
Item 3
```[tasklist]
### Child Issues
- [ ] https://github.com/near/data-platform/issues/23
- [x] Build an indexer for BOS components
- [ ] https://github.com/near/data-platform/issues/22
- [ ] https://github.com/near/data-platform/issues/27
- [ ] https://github.com/near/data-platform/issues/26
```
