### ISSUE TITLE
🔷 [Epic] Query + data pipeline to pull and pipe Apps to a page that qualify to Participate

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/data-platform#33]
### Description
(Overview of milestone or function governed by this epic)

### Success Criteria
- Pull all apps with description filled in 
- Pull all apps with tags that contains app + one of <Earn, Play, Develop, Engage>, they could add more but the first two are required
-  this should run on minimum the hourly basis to update registered apps
- This will run throughout now to after NEARCon

```[tasklist]
### Child Issues
- [ ] https://github.com/near/data-platform/issues/32
- [ ] https://github.com/near/data-platform/issues/26
- [ ] https://github.com/near/data-platform/issues/36
```
