### ISSUE TITLE
🔷 [Epic] Application Publishing Flow Rework + Standardize App Metadata

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/data-platform#8]
### Description
(Overview of milestone or function governed by this epic)
### Success Criteria
(Evaluate how this epic could be considered as complete and success)
### Resources
(Relevant documentation, Figma links, and other reference material)
Item 1
Item 2
Item 3
```[tasklist]
### Child Issues
[ ] https://github.com/near/github-project-test/issues/1
[ ] https://github.com/near/github-project-test/issues/2
[ ] https://github.com/near/github-project-test/issues/3
```
```[tasklist]
### dependencies/blocked
[ ] https://github.com/near/github-project-test/issues/1
[ ] https://github.com/near/github-project-test/issues/2
[ ] https://github.com/near/github-project-test/issues/3
```

```[tasklist]
### Tasks
- [x] Filter on time-based tag sequence
- [x] Get frozen dataset from near.org/applications for validation
- [x] Create table, merging applications unlablled and manually labeled
- [x] Adjust a query runner to upload to app-store.json after adding manual entries
- [ ] Evaluate several Classification Models to predict on Category on category_label (section_title later...)
- [ ] https://github.com/near/near-discovery-components/pull/475
- [x] Add corrected tags aggregation
- [ ] Add corrected image extraction from publishing transactions without metadata in db
```
